[build]
  publish = "scsmission.org/public"
  command = "cd scsmission.org && npm install && npx tinacms build -c \"hugo --minify --gc --themesDir ../..\""
  
[build.environment]
  HUGO_VERSION = "0.73.0"
  HUGO_THEME = "repo"
  HUGO_BASEURL = "/"
