baseURL = "https://scsmission.org"
disableLanguages = []
disqusShortname = "SCS-SLC"
paginate = "6"
summaryLength = "10"
theme = "educenter-hugo"
title = "Sri Caitanya Saraswat Mission | Salt Lake City"
[Languages.en]
contentDir = "content/english"
copyright = "Copyright &copy; 2021 a hugo theme by [Themefisher](https://themefisher.com/hugo-themes/)"
home = "Home"
languageCode = "en-us"
languageName = "En"
weight = 1
[[Languages.en.menu.footer]]
name = "event"
url = "event/"
[[Languages.en.menu.main]]
name = "About"
url = "about/"
weight = 1
[[Languages.en.menu.main]]
name = "kirtan"
url = "kirtan/"
weight = 2
[[Languages.en.menu.main]]
name = "events"
url = "event/"
[[Languages.en.menu.main]]
name = "blog"
url = "blog/"
weight = 4
[[Languages.en.menu.main]]
name = "Contact"
url = "contact/"
weight = 5
[params]
address = "745 S 700 E, Salt Lake City, UT 84102"
author = "Sri Caitanya Saraswat Mission"
contact_form_action = ""
description = "A beautiful like-minded conscious community hiding in the neighborhood of Salt Lake City."
email = ""
google_analitycs_id = ""
logo = "images/logo.png"
mobile = ""
top_header = true
[params.cookies]
enable = false
expire_days = 2
[params.map]
enable = true
gmap_api = "https://maps.googleapis.com/maps/api/js?key=AIzaSyCcABaamniA6OL5YvYSpB3pFMNrXwXnLwU&libraries=places"
map_latitude = "40.75314460022046"
map_longitude = "-111.87063827342762"
map_marker = "images/marker.png"
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "plugins/animate/animate.css"
[[params.plugins.css]]
link = "plugins/venobox/venobox.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/venobox/venobox.min.js"
[[params.plugins.js]]
link = "plugins/filterizr/jquery.filterizr.min.js"
[[params.plugins.js]]
link = "plugins/google-map/gmap.js"
[params.preloader]
enable = false
preloader = "images/preloader.gif"
[params.subscription]
enable = false
mailchimp_form_action = "https://gmail.us4.list-manage.com/subscribe/post?u=463ee871f45d2d93748e77cad&amp;id=a0a2c6d074"
mailchimp_form_name = "b_463ee871f45d2d93748e77cad_a0a2c6d074"
[[params.social]]
icon = "ti-facebook"
link = "https://www.facebook.com/scsmission/"
title = "facebook"
[[params.social]]
icon = "ti-instagram"
link = "https://www.instagram.com/scsmission/"
title = "instagram"
